title: Ramprakash Chandrashekar
description: Self driven techie with a penchant for rapid prototyping using microcontrollers and development boards.
theme: jekyll-theme-cayman
# theme: jekyll-theme-hacker

